#!/usr/bin/env python3
"""P1 deliverable — the Ledger sheet: a single self-contained HTML page
rendering every token, ramp, type role, stamp variant, and pattern swatch in
both modes. Fonts + patterns are inlined (base64) so the file previews
anywhere. Output: docs/ledger-sheet.html

Run from the app root:  python3 scripts/build_ledger_sheet.py
"""

import base64
import json
from pathlib import Path

APP = Path(__file__).resolve().parent.parent
PUB = APP / "narjes_custom" / "public"
TOKENS = json.loads((PUB / "tokens.json").read_text())
OUT = APP / "docs" / "ledger-sheet.html"


def font_face(family, filename, weight, unicode_range=None):
    data = base64.b64encode((PUB / "fonts" / filename).read_bytes()).decode()
    ur = f"unicode-range:{unicode_range};" if unicode_range else ""
    return (
        f'@font-face{{font-family:"{family}";font-weight:{weight};'
        f"font-display:swap;{ur}"
        f'src:url(data:font/woff2;base64,{data}) format("woff2");}}'
    )


def pattern_uri(name):
    data = base64.b64encode((PUB / "patterns" / name).read_bytes()).decode()
    return f"data:image/svg+xml;base64,{data}"


fonts_css = "\n".join([
    font_face("Fraunces", "fraunces-latin-400-600.woff2", "400 600"),
    font_face("IBM Plex Sans", "ibm-plex-sans-latin-400-600.woff2", "400 600"),
    font_face("IBM Plex Mono", "ibm-plex-mono-latin-400.woff2", "400"),
    font_face("IBM Plex Mono", "ibm-plex-mono-latin-500.woff2", "500"),
    font_face("IBM Plex Mono", "ibm-plex-mono-latin-600.woff2", "600"),
    font_face("Amiri", "amiri-arabic-400.woff2", "400",
              "U+0600-06FF,U+0750-077F,U+FB50-FDFF,U+FE70-FEFF"),
    font_face("IBM Plex Sans Arabic", "ibm-plex-sans-arabic-arabic-400.woff2", "400",
              "U+0600-06FF,U+0750-077F,U+FB50-FDFF,U+FE70-FEFF"),
])

vars_css = (PUB / "css" / "narjes-vars.css").read_text()
# narjes-vars.css keys dark mode off [data-theme="dark"] on :root — the sheet
# toggles the same attribute on <html>, so it works unchanged.

ramps_html = ""
for ramp, stops in TOKENS["ramps"].items():
    cells = "".join(
        f'<div class="stop"><div class="chip" style="background:{v}"></div>'
        f'<span>{k}</span></div>'
        for k, v in stops.items()
    )
    ramps_html += f'<div class="ramp"><h4>{ramp}</h4><div class="stops">{cells}</div></div>'
ramps_html += (
    '<div class="ramp"><h4>mint (logo)</h4><div class="stops">'
    f'<div class="stop"><div class="chip" style="background:{TOKENS["singles"]["mint"]}"></div>'
    '<span>mint</span></div></div></div>'
)

sem_rows = ""
for key in TOKENS["semantic"]["light"]:
    if key == "shadow-rgb":
        continue
    sem_rows += (
        f'<tr><td class="mono">--n-{key}</td>'
        f'<td><span class="chip-sm" style="background:var(--n-{key})"></span>'
        f'<span class="mono val-l">{TOKENS["semantic"]["light"][key]}</span></td>'
        f'<td><span class="mono val-d">{TOKENS["semantic"]["dark"][key]}</span></td></tr>'
    )

html = f"""<!-- GENERATED by scripts/build_ledger_sheet.py — edit tokens.json, not this file -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Narjes Ledger — token sheet</title>
<style>
{fonts_css}
{vars_css}
:root {{ color-scheme: light dark; }}
* {{ box-sizing: border-box; }}
body {{
  margin: 0; padding: 32px 24px 64px;
  background: var(--n-bg); color: var(--n-text);
  font-family: var(--n-font-body); font-size: 13px; line-height: 20px;
  max-width: 1000px; margin-inline: auto;
  background-image: url({pattern_uri('grain.svg')});
}}
[data-theme="dark"] body {{ background-image: none; }}
h1 {{ font-family: var(--n-font-display); font-size: 38px; line-height: 44px; font-weight: 600; margin: 0; }}
h2 {{ font-family: var(--n-font-display); font-size: 20px; line-height: 28px; margin: 40px 0 12px; border-bottom: 1px solid var(--n-border); padding-bottom: 8px; }}
h4 {{ font-family: var(--n-font-mono); font-size: 11px; text-transform: uppercase; letter-spacing: .08em; color: var(--n-text-3); margin: 12px 0 6px; }}
.sub {{ color: var(--n-text-2); margin: 4px 0 0; }}
.toggle {{ position: fixed; top: 16px; right: 16px; background: var(--n-surface); color: var(--n-text);
  border: 1px solid var(--n-border-strong); border-radius: 8px; padding: 6px 14px; cursor: pointer; font: inherit; }}
.stops {{ display: flex; gap: 4px; flex-wrap: wrap; }}
.stop {{ text-align: center; font-family: var(--n-font-mono); font-size: 10px; color: var(--n-text-3); }}
.chip {{ width: 64px; height: 36px; border-radius: 6px; border: 1px solid var(--n-border); }}
.chip-sm {{ display: inline-block; width: 20px; height: 14px; border-radius: 3px; border: 1px solid var(--n-border); vertical-align: -2px; margin-inline-end: 8px; }}
table {{ border-collapse: collapse; width: 100%; }}
td, th {{ padding: 6px 10px; border-bottom: 1px solid var(--n-border); text-align: left; }}
.mono {{ font-family: var(--n-font-mono); font-size: 12px; }}
[data-theme="light"] .val-d, .val-d {{ opacity: .55; }}
.type-sample {{ margin: 14px 0; }}
.role {{ font-family: var(--n-font-mono); font-size: 10px; text-transform: uppercase; letter-spacing: .08em; color: var(--n-text-3); }}
.t-display-xl {{ font-family: var(--n-font-display); font-size: 38px; line-height: 44px; font-weight: 600; }}
.t-display {{ font-family: var(--n-font-display); font-size: 28px; line-height: 34px; font-weight: 600; }}
.t-display-sm {{ font-family: var(--n-font-display); font-size: 20px; line-height: 28px; font-weight: 600; }}
.t-body {{ font-size: 13px; }}
.t-ledger {{ font-family: var(--n-font-mono); font-variant-numeric: tabular-nums; }}
.t-kpi {{ font-family: var(--n-font-mono); font-size: 32px; line-height: 38px; font-weight: 600; font-variant-numeric: tabular-nums; }}
.t-caps {{ font-family: var(--n-font-mono); font-size: 11px; font-weight: 500; text-transform: uppercase; letter-spacing: .08em; }}
.stamps {{ display: flex; gap: 12px; flex-wrap: wrap; align-items: center; }}
.stamp {{ display: inline-flex; align-items: center; gap: 6px; height: 22px; padding: 0 8px;
  border: 1.5px solid currentColor; border-radius: 4px;
  font-family: var(--n-font-mono); font-size: 11px; font-weight: 500;
  text-transform: uppercase; letter-spacing: .08em; white-space: nowrap; }}
.stamp .dot {{ width: 6px; height: 6px; border-radius: 50%; background: currentColor; }}
.st-outline {{ color: var(--n-primary); background: transparent; }}
.st-tint {{ color: var(--n-accent-text); background: var(--n-accent-bg); border-color: transparent; }}
.st-solid {{ color: var(--n-primary-text-on); background: var(--n-primary); border-color: var(--n-primary); }}
.st-stamped {{ color: var(--n-primary); transform: rotate(-2deg);
  box-shadow: 0 0 0 1.5px var(--n-bg), 0 0 0 3px currentColor; }}
.st-stamped.danger {{ color: var(--n-danger); }}
.cards {{ display: flex; gap: 16px; flex-wrap: wrap; }}
.card {{ background: var(--n-surface); border: 1px solid var(--n-border); padding: 24px; width: 180px; }}
.e1 {{ box-shadow: var(--n-e1); border-radius: 12px; }}
.e2 {{ box-shadow: var(--n-e2); border-radius: 12px; }}
.e3 {{ box-shadow: var(--n-e3); border-radius: 16px; }}
.btns {{ display: flex; gap: 12px; flex-wrap: wrap; align-items: center; }}
.btn {{ font: inherit; font-weight: 500; border-radius: 8px; padding: 7px 16px; cursor: pointer; border: 1px solid transparent; }}
.btn-primary {{ background: var(--n-primary); color: var(--n-primary-text-on); }}
.btn-default {{ background: var(--n-surface); color: var(--n-text); border-color: var(--n-border-strong); }}
.btn-danger {{ background: transparent; color: var(--n-danger-text); border-color: var(--n-danger); }}
input.demo {{ font: inherit; background: var(--n-surface); color: var(--n-text);
  border: 1px solid var(--n-border-strong); border-radius: 8px; padding: 7px 12px; }}
input.demo:focus {{ outline: none; border-color: var(--n-focus); box-shadow: 0 0 0 2px var(--n-selection); }}
.patterns {{ display: flex; gap: 16px; flex-wrap: wrap; }}
.pattern {{ width: 220px; height: 140px; border-radius: 12px; border: 1px solid var(--n-border); position: relative; overflow: hidden; }}
.pattern span {{ position: absolute; bottom: 8px; left: 10px; font-family: var(--n-font-mono); font-size: 10px; }}
.p-vine-l {{ background: #F2F4F1 url({pattern_uri('vine-light.svg')}); }}
.p-vine-l::after {{ content: ""; position: absolute; inset: 0; background: #F2F4F1; opacity: .92; }}
.p-vine-l span {{ z-index: 1; color: #4C544E; }}
.p-vine-d {{ background: #121714 url({pattern_uri('vine-dark.svg')}); }}
.p-vine-d::after {{ content: ""; position: absolute; inset: 0; background: #121714; opacity: .93; }}
.p-vine-d span {{ z-index: 1; color: #B7C0B9; }}
.ar {{ font-family: var(--n-font-display); }}
</style>
<button class="toggle" onclick="
  const r = document.documentElement;
  r.setAttribute('data-theme', r.getAttribute('data-theme') === 'dark' ? 'light' : 'dark');
  this.textContent = r.getAttribute('data-theme') === 'dark' ? 'Paper ☀' : 'Ink ☾';
">Ink ☾</button>

<h1>Narjes Ledger</h1>
<p class="sub">Token sheet — every color, type role, stamp, and pattern. Toggle Paper/Ink top-right.
Generated from <span class="mono">tokens.json</span>; the P12 contrast matrix covers every pairing shown.</p>

<h2>Ramps</h2>
{ramps_html}

<h2>Semantic tokens</h2>
<table>
<tr><th>Token</th><th>Paper</th><th>Ink</th></tr>
{sem_rows}
</table>

<h2>Type roles</h2>
<div class="type-sample"><div class="role">display-xl · Fraunces 600 · 38/44</div>
<div class="t-display-xl">Home Dashboard</div></div>
<div class="type-sample"><div class="role">display · 28/34 — Arabic falls to Amiri</div>
<div class="t-display">Confirm &amp; Create Order · <span class="ar">زينب حسن</span></div></div>
<div class="type-sample"><div class="role">display-sm · 20/28</div>
<div class="t-display-sm">Revenue — last 14 days</div></div>
<div class="type-sample"><div class="role">body · IBM Plex Sans · 13/20 — Arabic falls to Plex Arabic</div>
<div class="t-body">Delivery scheduled for Thursday to Baghdad — التوصيل يوم الخميس إلى بغداد</div></div>
<div class="type-sample"><div class="role">ledger · IBM Plex Mono · tnum</div>
<div class="t-ledger">SO-2114 · 07701 234 567 · 148,000 IQD</div></div>
<div class="type-sample"><div class="role">kpi · 32/38 semibold</div>
<div class="t-kpi">1,482,000</div></div>
<div class="type-sample"><div class="role">micro-caps · 11/16 · 0.08em</div>
<div class="t-caps">Order · Customer · Workspace · Insights</div></div>

<h2>The Ink Stamp</h2>
<div class="stamps">
<span class="stamp st-outline"><span class="dot"></span>New</span>
<span class="stamp st-tint"><span class="dot"></span>In Design</span>
<span class="stamp st-solid"><span class="dot"></span>In Delivery</span>
<span class="stamp st-stamped"><span class="dot"></span>Paid</span>
<span class="stamp st-stamped danger"><span class="dot"></span>Cancelled</span>
</div>
<p class="sub">outline → provisional · tint → in progress · solid → active ·
stamped (−2°, double border) → terminal states only.</p>

<h2>Buttons &amp; controls</h2>
<div class="btns">
<button class="btn btn-primary">Create order</button>
<button class="btn btn-default">Save changes</button>
<button class="btn btn-danger">Cancel order</button>
<input class="demo" placeholder="Search orders, customers…">
</div>

<h2>Elevation</h2>
<div class="cards">
<div class="card e1">e1 — cards</div>
<div class="card e2">e2 — popovers</div>
<div class="card e3">e3 — dialogs</div>
</div>

<h2>Patterns</h2>
<div class="patterns">
<div class="pattern p-vine-l"><span>narjes vine · paper (shown boosted)</span></div>
<div class="pattern p-vine-d"><span>narjes vine · ink (shown boosted)</span></div>
</div>
"""

OUT.write_text(html)
print(f"wrote {OUT} ({OUT.stat().st_size / 1024:.0f} KB)")
