#!/usr/bin/env python3
"""P12.1 — mechanical WCAG contrast matrix for every semantic pairing in
tokens.json, both modes. Writes docs/CONTRAST.md and exits non-zero if any
required pairing fails its threshold (AA: 4.5 body text, 3.0 large/UI).

Run from the app root:  python3 scripts/contrast_check.py
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TOKENS = ROOT / "narjes_custom" / "public" / "tokens.json"
OUT = ROOT / "docs" / "CONTRAST.md"


def srgb(channel):
    channel /= 255
    return channel / 12.92 if channel <= 0.04045 else ((channel + 0.055) / 1.055) ** 2.4


def luminance(hexcolor):
    hexcolor = hexcolor.lstrip("#")
    r, g, b = (int(hexcolor[i : i + 2], 16) for i in (0, 2, 4))
    return 0.2126 * srgb(r) + 0.7152 * srgb(g) + 0.0722 * srgb(b)


def ratio(fg, bg):
    l1, l2 = sorted((luminance(fg), luminance(bg)), reverse=True)
    return (l1 + 0.05) / (l2 + 0.05)


def build_pairings(sem, ramps, singles):
    """(label, fg, bg, threshold) per mode — the promises P1.1 makes."""
    r = lambda name, stop: ramps[name][str(stop)]
    return [
        ("body text on canvas", sem["text"], sem["bg"], 4.5),
        ("body text on surface", sem["text"], sem["surface"], 4.5),
        ("body text on raised", sem["text"], sem["raised"], 4.5),
        ("secondary text on canvas", sem["text-2"], sem["bg"], 4.5),
        ("secondary text on surface", sem["text-2"], sem["surface"], 4.5),
        ("tertiary text on surface (large/meta)", sem["text-3"], sem["surface"], 3.0),
        ("primary button label", sem["primary-text-on"], sem["primary"], 4.5),
        ("link on canvas", sem["link"], sem["bg"], 4.5),
        ("link on surface", sem["link"], sem["surface"], 4.5),
        ("accent text on accent tint", sem["accent-text"], sem["accent-bg"], 4.5),
        ("danger text on danger tint", sem["danger-text"], sem["danger-bg"], 4.5),
        ("success text on success tint", sem["success"], sem["success-bg"], 4.5),
        ("info text on info tint", sem["info"], sem["info-bg"], 4.5),
        ("focus ring on canvas (UI)", sem["focus"], sem["bg"], 3.0),
        ("border-strong on surface (UI)", sem["border-strong"], sem["surface"], 1.2),
        ("text on selection", sem["text"], sem["selection"], 4.5),
    ]


tokens = json.loads(TOKENS.read_text())
LIGHT = tokens["semantic"]["light"]
DARK = tokens["semantic"]["dark"]

rows, failures = [], []
for mode, sem in (("Paper (light)", LIGHT), ("Ink (dark)", DARK)):
    for label, fg, bg, threshold in build_pairings(sem, tokens["ramps"], tokens["singles"]):
        value = ratio(fg, bg)
        ok = value >= threshold
        if not ok:
            failures.append((mode, label, value, threshold))
        rows.append(
            f"| {mode} | {label} | `{fg}` on `{bg}` | {value:.2f} | {threshold} |"
            f" {'✅' if ok else '❌'} |"
        )

OUT.parent.mkdir(exist_ok=True)
OUT.write_text(
    "# Narjes Ledger — contrast matrix (generated by scripts/contrast_check.py)\n\n"
    "WCAG AA: 4.5:1 body text, 3:1 large text / UI components.\n\n"
    "| Mode | Pairing | Colors | Ratio | Min | Pass |\n|---|---|---|---|---|---|\n"
    + "\n".join(rows)
    + "\n"
)
print(f"wrote {OUT} — {len(rows)} pairings, {len(failures)} failures")
for f in failures:
    print(f"  FAIL {f[0]} · {f[1]}: {f[2]:.2f} < {f[3]}")
sys.exit(1 if failures else 0)
