#!/usr/bin/env python3
"""Self-host the Narjes Ledger font families (plan P2.9).

Pulls Google Fonts' own unicode-range-split woff2 files (they are already
subset per script — latin / latin-ext / arabic), stores them under
public/fonts/, and emits public/scss/narjes/_fonts.scss with local URLs.
All families are OFL. Run once, commit the outputs; re-run only to change
the font set.

Run from the app root:  python3 scripts/fetch_fonts.py
"""

import re
import subprocess
from pathlib import Path

APP = Path(__file__).resolve().parent.parent / "narjes_custom"
FONTS_DIR = APP / "public" / "fonts"
OUT_SCSS = APP / "public" / "scss" / "narjes" / "_fonts.scss"

UA = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
)

# Subsets kept deliberately tight for the 380 KB budget (plan P2.9): the
# shop's data is Latin + Arabic only, and the Arabic companion faces don't
# need their own latin splits — Plex Sans / Fraunces sit before them in the
# fallback stacks and claim every Latin glyph first.
FAMILIES = [
    ("Fraunces", "wght@400;600", {"latin"}),
    ("IBM Plex Sans", "wght@400;500;600", {"latin"}),
    ("IBM Plex Mono", "wght@400;500;600", {"latin"}),
    ("IBM Plex Sans Arabic", "wght@400;500;600", {"arabic"}),
    # Amiri 400 only: it's the Arabic display companion for Fraunces moments;
    # 700 would cost another 100 KB against the 380 KB budget for a weight
    # the mock never uses.
    ("Amiri", "wght@400", {"arabic"}),
]

# Baseline harmonization (plan P1.2): Amiri sits visually small next to
# Fraunces; Plex Arabic is metric-compatible with Plex Sans and needs nothing.
EXTRA_DESCRIPTORS = {
    "Amiri": "\tsize-adjust: 106%;\n\tascent-override: 105%;\n",
}

BLOCK_RE = re.compile(r"/\*\s*([a-z-]+)\s*\*/\s*@font-face\s*\{([^}]+)\}", re.M)


def fetch(url):
    # curl: the system Python has no CA bundle installed
    return subprocess.run(
        ["curl", "-fsSL", "--max-time", "60", "-A", UA, url],
        check=True, capture_output=True,
    ).stdout


def main():
    import hashlib

    FONTS_DIR.mkdir(parents=True, exist_ok=True)
    out = [
        "/* GENERATED by scripts/fetch_fonts.py — self-hosted OFL families",
        "   (Fraunces, IBM Plex Sans/Mono/Arabic, Amiri). DO NOT HAND-EDIT. */\n",
    ]
    total = 0
    for family, axis, subsets in FAMILIES:
        css_url = (
            "https://fonts.googleapis.com/css2?family="
            + family.replace(" ", "+") + ":" + axis + "&display=swap"
        )
        css = fetch(css_url).decode()
        slug = family.lower().replace(" ", "-")

        # Google serves the same variable-font file for every weight of some
        # families — download each unique file once and collapse its weights
        # into a single range descriptor.
        by_file = {}  # (subset, style, hash) -> {weights, data, unicode_range}
        for subset, body in BLOCK_RE.findall(css):
            if subset not in subsets:
                continue
            weight = re.search(r"font-weight:\s*(\d+)", body).group(1)
            style = re.search(r"font-style:\s*(\w+)", body).group(1)
            url = re.search(r"src:\s*url\((\S+?)\)", body).group(1)
            unicode_range = re.search(r"unicode-range:\s*([^;]+);", body).group(1)
            data = fetch(url)
            key = (subset, style, hashlib.md5(data).hexdigest())
            entry = by_file.setdefault(
                key, {"weights": [], "data": data, "unicode_range": unicode_range}
            )
            entry["weights"].append(int(weight))

        for (subset, style, _), entry in by_file.items():
            weights = sorted(entry["weights"])
            wmin, wmax = weights[0], weights[-1]
            wlabel = f"{wmin}" if wmin == wmax else f"{wmin}-{wmax}"
            fname = f"{slug}-{subset}-{wlabel}{'-i' if style != 'normal' else ''}.woff2"
            (FONTS_DIR / fname).write_bytes(entry["data"])
            total += len(entry["data"])
            out.append("@font-face {")
            out.append(f'\tfont-family: "{family}";')
            out.append(f"\tfont-style: {style};")
            out.append(f"\tfont-weight: {wmin if wmin == wmax else f'{wmin} {wmax}'};")
            out.append("\tfont-display: swap;")
            if family in EXTRA_DESCRIPTORS:
                out.append(EXTRA_DESCRIPTORS[family].rstrip("\n"))
            out.append(
                f'\tsrc: url("/assets/narjes_custom/fonts/{fname}") format("woff2");'
            )
            out.append(f"\tunicode-range: {entry['unicode_range'].strip()};")
            out.append("}\n")
    OUT_SCSS.write_text("\n".join(out))
    print(f"fonts: {total / 1024:.0f} KB woff2 total (budget 380 KB)")
    print(f"wrote {OUT_SCSS}")


if __name__ == "__main__":
    main()
